### ISSUE TITLE
fs.move folder report EPERM error

### ISSUE THREAD

**Issue by fpsqdb** [jprichardson/node-fs-extra#684] opened 2019-05-14 03:04 UTC
- **Operating System:** Windows 10 1809 17763.475
- **Node.js version:** 7.9.0 (within electron 1.7.9)
- **`fs-extra` version:** 8.0.0

fs.move folder will cause EPERM error, it works fine if downgrade to 7.0.1.

**Comment by manidlou** [comment] 2019-05-15 07:06
We added checking paths in v8.0.1 that stats src and dest. Seems like the running process doesn't have permissions to stat the folder! Windows is known to throw EPERM error in different situations!

I am thinking maybe we should remove path checking in `move`! My primary goal was to be consistent with `copy` as well as avoiding possible future bugs. But if we believe it is not that needed for `move`, I am fine removing it! We can take care of the :bug:s once they show up!

**Comment by manidlou** [comment] 2019-05-15 17:10
Also could be because we disabled `graceful-fs` (#664) and switched to native `fs` as `graceful-fs` needs to be updated. Basically, `graceful-fs` has some [improvements](https://github.com/isaacs/node-graceful-fs#improvements-over-fs-module) over native `fs` like handling EPERM error on windows when trying to rename a file.

**Comment by RyanZim** [comment] 2019-05-21 15:08
Has anyone else been able to reproduce this? @fpsqdb can you write a failing test case?

**Comment by malept** [comment] 2019-05-21 15:35
FWIW, I can reproduce this in the [Electron Packager testsuite](https://travis-ci.org/electron-userland/electron-packager/jobs/532057567#L1210-L1217), but unfortunately since I don't personally own a Windows machine, it would be rather difficult for me to write a minimal testcase.

**Comment by manidlou** [comment] 2019-05-22 03:32
Another thing is I am wondering if it happens outside of electron as well! Has anyone been experiencing this in environments other than electron?

**Comment by fpsqdb** [comment] 2019-05-22 03:47
[electron-quick-start.zip](https://github.com/jprichardson/node-fs-extra/files/3205486/electron-quick-start.zip)
```
npm install

npm run start
```
If there are no errors, delete the `dest/test` folder and try again.

![20190522114142](https://user-images.githubusercontent.com/6482819/58146098-3ef23280-7c87-11e9-99f9-aa4388abfb16.png)

**Comment by malept** [comment] 2019-05-22 06:03
The Electron Packager tests run in a Node environment, not an Electron one.

**Comment by manidlou** [comment] 2019-05-22 06:29
Looking at the provided travis log, `EPERM` error comes from `rename` and the only thing that is changed in the internal [rename](https://github.com/jprichardson/node-fs-extra/blob/master/lib/move/move.js#L48) function of `move` from fs-extra `7.0.1` to `8.0.1` is that we use native `fs` instead of `graceful-fs` temporarily (#664). My gut tells me once we switch back to `graceful-fs` this will be resolved. Basically, this is one of the reasons (advantages) that we use `graceful-fs` as a dependency so that we don't need to do extra work for cases like this here in our codebase!

**Comment by malept** [comment] 2019-06-27 16:54
FYI, `graceful-fs` 4.2.0 has been released with the `fs.stat()` fix.

**Comment by RyanZim** [comment] 2019-06-27 19:50
On it

**Closed** 2019-06-28 16:18 UTC
Labels: awaiting-reply, feature-move, needs-confirmed, platform-windows
