### ISSUE TITLE
emptyDir throws Error if no callback is provided

### ISSUE THREAD

**Issue by deyhle** [jprichardson/node-fs-extra#135] opened 2015-05-19 09:26 UTC
I use `emptyDir(…)` in a mocha `after` hook to delete files generated by my test cases:

``` js
  after('remove compiled files', function() {
    fs.emptyDir('./build');
  });
```

This throws the following error in node's `fs` (?) if no `callback` argument is provided:

```
TypeError: undefined is not a function
    at FSReqWrap.oncomplete (fs.js:95:15)
```

If I provide an empty function as callback, all is fine:

``` js
  after('remove compiled files', function() {
    fs.emptyDir('./build', function(){});
  });
```

I'm on Node v0.12.2.

**Comment by jprichardson** [comment] 2015-05-19 13:18
This definitely shouldn't throw an error if no callback is provided, but why don't you just do this in meantime?

```js
after('remove compiled files', function(done) {
    fs.emptyDir('./build', done);
  });
```

**Comment by RyanZim** [comment] 2016-10-27 17:11
@deyhle I can't reproduce, perhaps this has been fixed?

**Comment by RyanZim** [comment] 2016-11-05 13:17
Going to assume this is fixed. Closing.

**Closed by RyanZim** 2016-11-05 13:17 UTC
Labels: awaiting-reply, enhancement, needs-confirmed
