### ISSUE TITLE
consider using fs.access to remove deprecated warnings for fs.exists

### ISSUE THREAD

**Issue by jprichardson** [jprichardson/node-fs-extra#127] opened 2015-04-17 16:05 UTC
See: https://github.com/futagoza/efe/blob/39538c05bdab0d5ed947a8f3ae8b6b6d11de71e7/index.js#L57

**Comment by TheJaredWilcurt** [comment] 2016-07-09 16:13
Yes, please implement `fs.exists` and more importantly `fs.existsSync` so that it will continue to work as expected, returning a simple boolean value. I swear, the Node core devs have no concept of how real humans think. "Gee I want to delete something, should I call it fs.delete, or some bullshit like fs.unlink", complete idiots.

**Comment by RyanZim** [comment] 2016-10-27 12:46
Removing from v1.0.0 milestone, see https://github.com/jprichardson/node-fs-extra/issues/145#issuecomment-256533811 for details.

**Comment by TheJaredWilcurt** [comment] 2016-10-27 12:50
<p align="center"><img src="https://cloud.githubusercontent.com/assets/4629794/19767771/58e6900c-9c22-11e6-841e-d137207835ff.gif" alt="you make me sad.gif"></p>

**Comment by RyanZim** [comment] 2016-10-27 13:03
@TheJaredWilcurt Sorry to disappoint you, there are a lot of things we would like to do, but right now first priority is shipping v1.0.0 (preferably this week).

`fs.existsSync` is no longer depreciated, so that can be used safely.

I recommend using https://www.npmjs.com/package/path-exists for `fs.exists` for the time being.

**Comment by jprichardson** [comment] 2016-10-27 14:33
Does using `fs.exists` even output a warning? I've never seen it and I use it frequently.

**Comment by RyanZim** [comment] 2016-10-27 15:41
@jprichardson Not that I'm aware of. I think it might in older releases.

**Comment by RyanZim** [comment] 2016-12-26 20:46
Going to close this since it is basically a dupe of https://github.com/jprichardson/node-fs-extra/issues/145.

**Closed by RyanZim** 2016-12-26 20:46 UTC
