### ISSUE TITLE
fs.copy seems to callback early if the destination file already exists

### ISSUE THREAD

**Issue by iantocristian** [jprichardson/node-fs-extra#113] opened 2015-02-11 12:40 UTC

**Comment by jprichardson** [comment] 2015-02-11 22:18
Presumably using the latest `fs-extra` version, right? This should have been solved in https://github.com/jprichardson/node-fs-extra/issues/98. Any way you can reproduce it or have a snippet of code? Thanks

**Comment by jprichardson** [comment] 2015-03-08 20:28
Closing since I believe this be solved with #98. Please reopen if this is still occurring with the latest version.

**Closed by jprichardson** 2015-03-08 20:28 UTC
