### ISSUE TITLE
v9.0.0 incompatible with Cypress. Throwing exception

### ISSUE THREAD

**Issue by Postavshik** [jprichardson/node-fs-extra#771] opened 2020-03-19 20:39 UTC
- **Operating System:**
macOS Mojave, v.10.14.6
- **Node.js version:**
v10.16.0
- **`fs-extra` version:**
v9.0.0

![image](https://user-images.githubusercontent.com/21285622/77112769-96704480-69f7-11ea-9c2b-bb7f8316914d.png)

Previous version 8.1.0 works just fine

**Comment by RyanZim** [comment] 2020-03-20 14:30
It's erroring out over an optional catch binding we use. What's puzzling is why you'd be getting this error on Node v10.16.0; as optional catch bindings are supported in Node since v10.0.0.

**Comment by 26medias** [comment] 2020-03-24 00:50
We have 16 prod repositories that broke on deploy, had to force 8.1.0 on all of them.

Do you have a fix planned for the latest version?

**Comment by RyanZim** [comment] 2020-03-24 15:21
@26medias The changelog clearly states that Node.js v10 or greater is required for fs-extra v9.

**Comment by Postavshik** [comment] 2020-03-24 16:35
I have Node v10 but still having issues

**Comment by RyanZim** [comment] 2020-03-24 17:05
@Postavshik That's what's puzzling. I'm not familiar with Cyprus myself; looks like some sort of browser testing solution; is this code trying to run in-browser or something?

**Comment by Postavshik** [comment] 2020-03-24 18:37
Cypress is the framework for web ui automation. The tests are executed in the browser (as far as I know). Why is having the issue - have no idea )

**Comment by RyanZim** [comment] 2020-03-24 18:42
fs-extra v9 uses option catch bindings, which work in Node v10+ Something in your toolchain doesn't support them, I don't know what.

**Comment by drom** [comment] 2020-03-24 20:18
That is only one minor feature that breaks Node 8. That we really need.

**Comment by retorquere** [comment] 2020-04-01 22:50
My tests on travis are failing because of this error. My travis logs claims it's running under node v11.10.1

**Comment by 26medias** [comment] 2020-04-02 00:29
Breaking a popular lib for everybody not on V10 is a little bit problematic isn't it?
Node V8 isn't deprecated. It's still widely popular.

Never tried this, but guess that might be the fix?
https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json

**Comment by ErisDS** [comment] 2020-04-02 10:12
Node v8 has been EOL since 31st Dec 2019: As shown here: 
https://nodejs.org/en/about/releases/
and here:
https://github.com/nodejs/Release/blob/master/schedule.json#L38

It is no longer supported widely, and nor should it be, as it is no longer being maintained.

fs-extra already has the minimum node version declared in the package.json engines field.

The feature that's being used here is [Optional Catch bindings](https://node.green/#ES2019-misc-optional-catch-binding) and is reported as widely supported in Node.js v10.

--- 

All of that being said, we're also seeing this error in an environment self-reporting as Node.js v12 and will update when we get to the bottom of it.

**Comment by retorquere** [comment] 2020-04-02 11:48
Maybe it's just terminology, but I don't understand what being reported as widely supported in v10 entails -- wouldn't any given node version (and forward, one should hope) unequivocally either support this or not support this, rather than being widely supported, which would imply that the majority of v10 installations support it, but not all?

**Comment by RyanZim** [comment] 2020-04-02 14:43
All Node 10 versions support optional catch bindings. I suspect most of the cases reporting problems in newer versions will be traced to using tooling with outdated JS parsers.

**Comment by retorquere** [comment] 2020-04-02 14:58
That's possible, but then that means "if you have node v10+ you're good to go" isn't true.

**Comment by retorquere** [comment] 2020-04-02 14:59
There's also the thing that I upgraded node to 13.8.0 on Travis and that solved the breakage for me. I didn't change any packages. So it's not strictly tools with outdated parsers, because that wouldn't be affected by an upgrade of node from v11 to v13 (right?)

**Comment by RyanZim** [comment] 2020-04-02 15:03
If we can get a reduced test case of stuff breaking on Node 10+; that would be very helpful.

**Comment by ErisDS** [comment] 2020-04-02 18:00
Sorry for the confusing "widely supported" term. The compatibility site I linked starts at 10.3.0, so I wasn't sure if it was introduced in 10.3.0 or before, but I see mousing over that the ui collapsed, and is reported in all 10.x versions: https://node.green/#ES2019-misc-optional-catch-binding.

In our case, the problem is likely to do with nvm or some similar tool. Different users can end up with different Node versions, and it can be tricky to track down what's installed where.

**Comment by retorquere** [comment] 2020-04-02 18:26
In my case it was 11.10.1 though. Travis reports the active nodejs before the tests start.

**Comment by ErisDS** [comment] 2020-04-02 18:37
@retorquere this repo runs tests on travis with Node 11 - so it should be possible to add a minimal test case to demonstrate what fails on Node 11?

**Comment by retorquere** [comment] 2020-04-03 23:45
My mistake -- there must be something odd on Travis, but I can confirm it breaks with v9 but works with v10.

**Comment by rushilsrivastava** [comment] 2020-04-10 09:03
@ErisDS I am also facing this exact issue described [here](https://forum.ghost.org/t/attempt-to-upgrade-2-to-3-fails/13170/6) on V12 as well. As mentioned in the thread, running `ghost run` works for me. However, `ghost start` fails with no response.

**Comment by oleksiydubovykTR** [comment] 2020-04-18 11:50
Same with Node v12.14.1 here, fine up to v8.0.1

**Comment by ricardogobbosouza** [comment] 2020-04-24 19:46
This problem happens only on MacOS.

**Comment by dubbha** [comment] 2020-04-26 23:16
> Same with Node v12.14.1 here, fine up to v8.0.1

this one is on Windows 10

**Comment by RyanZim** [comment] 2020-06-03 20:16
It's been over a month with no action here; gonna close this one out. Happy to reopen if there's a reduced test case of stuff breaking on Node 10+

**Closed by RyanZim** 2020-06-03 20:16 UTC

**Comment by Inventsable** [comment] 2020-06-08 03:36
I'm getting this error as an Adobe developer who has no choice but to use Node v8.6.0 for the next few years until the coming UXP platform, unfortunately updating Node isn't an option for me and this is a dependency of another library I'm trying to use.

Any recommendations of versions of fs-extra to downgrade to or some kind of resolution/fix for those of us who can't upgrade Node would be appreciated

**Comment by RyanZim** [comment] 2020-06-08 17:06
@Inventsable any fs-extra version below v9 should work on Node 8

**Comment by rmlzy** [comment] 2020-08-13 06:29
`"fs-extra": "8.1.0"` working
