### ISSUE TITLE
TypeError: Cannot read property 'code' of null

### ISSUE THREAD

**Issue by artemave** [jprichardson/node-fs-extra#674] opened 2019-04-27 13:11 UTC
- **Operating System:**
Ubuntu 14.04
- **Node.js version:**
11.14.0
- **`fs-extra` version:**
7.0.1

My travis-ci build (runs on cron - so not triggered by code changes) suddenly started getting this error:
```
 TypeError: Cannot read property 'code' of null
      at rimrafSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:257:12)
      at options.readdirSync.forEach.f (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:39)
      at Array.forEach (<anonymous>)
      at rmkidsSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
      at rmdirSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
      at rimrafSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
      at options.readdirSync.forEach.f (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:39)
      at Array.forEach (<anonymous>)
      at rmkidsSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
      at rmdirSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
      at rimrafSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
      at options.readdirSync.forEach.f (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:39)
      at Array.forEach (<anonymous>)
      at rmkidsSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
      at rmdirSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
      at rimrafSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
      at options.readdirSync.forEach.f (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:39)
      at Array.forEach (<anonymous>)
      at rmkidsSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
      at rmdirSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
      at rimrafSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
      at options.readdirSync.forEach.f (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:39)
      at Array.forEach (<anonymous>)
      at rmkidsSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
      at rmdirSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
      at rimrafSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
      at options.readdirSync.forEach.f (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:39)
      at Array.forEach (<anonymous>)
      at rmkidsSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
      at rmdirSync (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
      at Object.rimrafSync [as removeSync] (/home/travis/build/featurist/create-hyperdom-app/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
      at TmpDir.remove (/home/travis/build/featurist/create-hyperdom-app/test/tmpDir.js:24:8)
      at Context.after (/home/travis/build/featurist/create-hyperdom-app/test/createAppSpec.js:68:22)
```

Looks as if fs-extra is catching an error, but the error turns out to be `null`. Not sure how this is possible.

Link to the build log https://travis-ci.org/featurist/create-hyperdom-app/builds/525146003

**Comment by GitNomster** [comment] 2019-05-17 06:31
Same problem

**Comment by RyanZim** [comment] 2019-05-17 12:47
Seems https://github.com/jprichardson/node-fs-extra/blob/master/lib/remove/rimraf.js#L251 must be showing that it's a directory, but we're getting `ENOTDIR` when we try to `rmdirSync`: https://github.com/jprichardson/node-fs-extra/blob/master/lib/remove/rimraf.js#L278 No idea how a path can simultaneously be both a directory and not a directory.

**Comment by RyanZim** [comment] 2019-05-21 15:11
@GitNomster What platform, Node, and `fs-extra` version?

**Comment by GitNomster** [comment] 2019-05-22 05:24
@RyanZim Platform: Win 10 x64; Node: 10.15.1; fs-extra: 8.0.1

**Comment by kingzez** [comment] 2019-09-20 04:58
Same question in Electron

**Comment by AryToNeX** [comment] 2020-05-13 23:44
I'm getting this one too! (and it's annoying)

**Comment by AryToNeX** [comment] 2020-05-14 00:07
Okay I found the culprit about this, and it has to do with Electron wrapping the "fs" module to handle asar files as directories.
ASAR archives are seen by Electron's "fs" module as directories, but they are files.

Solution: require "original-fs" if we're under Electron!

**Comment by RyanZim** [comment] 2020-06-03 20:33
If somebody could get a reduced test case for this (based on electron-quick-start, if it's an electron issue); that would be a tremendous help. Also, wondering how this plays out with `fs.rmdir` `recursive` option: https://github.com/jprichardson/node-fs-extra/issues/806.

**Comment by RyanZim** [comment] 2020-06-15 19:39
Possibly related: https://github.com/electron/electron/pull/23890

**Comment by KalebMatthews** [comment] 2020-09-24 15:40
Simple solution for electron is to set the process to not treat asar files differently with: `process.noAsar = true;` then after the process is finished whatever logic you are doing set it back to: `process.noAsar = false;`

**Comment by RyanZim** [comment] 2021-04-02 21:48
Closing since this hasn't ever been confirmed; and may have been fixed by electron. Happy to reopen in the future.

**Closed by RyanZim** 2021-04-02 21:48 UTC
Labels: feature-remove, needs-confirmed
