### ISSUE TITLE
Filter out non .pdf files during copy

### ISSUE THREAD

**Issue by soubhikchatterjee** [jprichardson/node-fs-extra#741] opened 2020-01-29 06:07 UTC
I am using "fs-extra" for one of my nodejs projects. I am using the .copy function to copy multiple files from one directory to another. Everything works fine except that I wish to copy only .pdf files from the source directory. I am using "filter options" to filter out all files but .pdf.

```
const fs = require('fs-extra')

const filterFunc = (src, dest) => {
 console.log(src, dest);
}

fs.copy('/tmp/mydir', '/tmp/mynewdir', { filter: filterFunc }, err => {
  if (err) return console.error(err)

  console.log('success!')
})
```

The console.log(src, dest); always logs the source and destination but not the file(s) that are bring copied. 

How can I copy only .pdf files?

Thanks

- **Operating System:**
Ubuntu: 18.04

- **Node.js version:**
12

- **`fs-extra` version:**
8.1.0

**Comment by manidlou** [comment] 2020-01-29 07:26
@soubhikchatterjee if I understand your case correctly, you want to copy only `.pdf` files from your source directory. With current `fs-extra` implementation you can achieve that like this:

```js
const fs = require('fs-extra')
const path = require('path')

const srcDir = 'src'
const destDir = 'dest'

const filterFunc = src => {
  return src === srcDir || path.extname(src) === '.pdf'
}

fs.copy(srcDir, destDir, { filter: filterFunc }, err => {
  if (err) return console.error(err)

  console.log('success!')
})
```

I understand that the filter function looks a little weird! The `fs-extra` team will work on that to make it more intuitive and easy to use for our users. The `src === srcDir` part is required in the filter function to get the expected behavior and the reason for that is with the current implementation, we check filter on each path including the root and that's why you need to check that in your filter function to make sure the copy operation moves forward to the next path under root directory.

**Comment by soubhikchatterjee** [comment] 2020-01-29 09:47
This would work if my source is a file and not an entire folder. Here I am trying to copy an entire directory from one place to another.


Thanks

**Comment by RyanZim** [comment] 2020-01-30 16:19
Closing to move discussion to https://github.com/jprichardson/node-fs-extra/issues/742.

**Closed by RyanZim** 2020-01-30 16:19 UTC
Labels: feature-copy, question
