### ISSUE TITLE
Rewrite move

### ISSUE THREAD

**Issue by manidlou** [jprichardson/node-fs-extra#548] opened 2018-02-03 00:17 UTC
The current implementation of `move()` is a little buggy. IDK why `fs.link` was used in the first place for moving on the same device as apposed to just using `fs.rename`! @jprichardson and @RyanZim may have better ideas here. Anyway, It seems like using `fs.link` and relying on `EPERM` error is not suitable approach to handle move operation. Please see #526, #492.

So I am not a fan of rewrite but I believe `move()` needs to be reconsidered for improved implementation anyway!

**Comment by RyanZim** [comment] 2018-02-03 01:31
@manidlou As far as switching away from `fs.link`, I'm fine with that. Do you have other changes in mind, or just that?

**Comment by manidlou** [comment] 2018-02-03 06:29
@RyanZim that's right. Switching from `fs.link` to `fs.rename` is the main thing I guess. However, AFAIK one of the main differences between `fs.link` and `fs.rename` is in how they behave when dest exists. I tested this one manually to see how `fs.rename` behaves for files and directories!

If we want to use `fs.rename` we need to consider these particularly when `{overwrite: false}` which is our default case: 

_(src and dest are on the same device)_
- when dest is a file that exists:
  - `fs.rename` doesn't throw any errors and replaces the contents of dest with src contents and removes src.

- when dest is a directory that exists:
  - if dest directory is empty, `fs.rename` doesn't throw any errors and moves the contents of src to dest and removes src.
  - if dest directory is not empty, `fs.rename` throws `ENOTEMPTY` error.

For the case of moving across devices, since that's pretty much the copy operation, maybe we can use our own `fs.copy` since `copy` handles both files and dirs itself, so that we don't need to have an extra implementation for copy inside `move` file.

**Comment by manidlou** [comment] 2018-02-03 06:35
I'll open up a PR shortly to see how we can improve this.

**Comment by RyanZim** [comment] 2018-04-06 15:28
Fixed in `v6-dev`; will be released later this month.

**Closed by RyanZim** 2018-04-06 15:28 UTC
Labels: enhancement, feature-move

**Comment by RyanZim** [comment] 2018-05-18 12:48
@zeroN1 That's intended behavior; fs-extra can't be overwriting a directory with a file.
