### ISSUE TITLE
Windows: mkdirs crashes / hangs with newline character

### ISSUE THREAD

**Issue by spoenemann** [jprichardson/node-fs-extra#740] opened 2020-01-20 08:46 UTC
This code never prints `done!`, but consumes lots of CPU (see #119):
```javascript
const fs = require('fs-extra');
fs.mkdirs('foo\nbar').then(() => {
    console.log('done!');
});
```

This code
```javascript
const fs = require('fs-extra');
fs.mkdirsSync('foo\nbar');
console.log('done!');
```
causes an error:
```
Error: EEXIST: file already exists, mkdir '...\fs-extra-bug'
    at Object.mkdirSync (fs.js:752:3)
    at mkdirsSync (...\fs-extra\lib\mkdirs\mkdirs-sync.js:31:9)
    at mkdirsSync (...\fs-extra\lib\mkdirs\mkdirs-sync.js:36:14)
    at mkdirsSync (...\fs-extra\lib\mkdirs\mkdirs-sync.js:37:7)
    at mkdirsSync (...\fs-extra\lib\mkdirs\mkdirs-sync.js:37:7)
    at mkdirsSync (...\fs-extra\lib\mkdirs\mkdirs-sync.js:37:7)
    at mkdirsSync (...\fs-extra\lib\mkdirs\mkdirs-sync.js:37:7)
    at mkdirsSync (...\fs-extra\lib\mkdirs\mkdirs-sync.js:37:7)
    at mkdirsSync (...\fs-extra\lib\mkdirs\mkdirs-sync.js:37:7)
    at mkdirsSync (...\fs-extra\lib\mkdirs\mkdirs-sync.js:37:7)
```

- **Operating System:** Windows 10 build 18362.592
- **Node.js version:** 10.15.3
- **`fs-extra` version:** 8.1.0

**Comment by RyanZim** [comment] 2020-01-20 16:24
Dupe of https://github.com/jprichardson/node-fs-extra/issues/524.

**Closed by RyanZim** 2020-01-20 16:24 UTC
