### ISSUE TITLE
please make sure the first argument in callback is error object

### ISSUE THREAD

**Issue by dead-horse** [jprichardson/node-fs-extra#233] opened 2016-04-06 10:17 UTC
https://github.com/jprichardson/node-fs-extra/blob/master/lib/copy/ncp.js#L237

**Comment by jprichardson** [comment] 2016-04-06 11:39
You're right, this should be fixed and be `Error?`.

**Comment by RyanZim** [comment] 2016-10-26 17:12
@jprichardson Can you elaborate a bit?

**Comment by jprichardson** [comment] 2016-10-26 17:55
@RyanZim `copy()` sometimes returns an array of errors instead of an Error object. This should be fixed for 1.0.0. The problem is... what should the behavior be like? First error? First error with an array of the other errors?

**Comment by RyanZim** [comment] 2016-10-26 18:03
@jprichardson Let's face it: _ncp.js need rewritten_. The resulting rewrite would probably make it small enough to inline in https://github.com/jprichardson/node-fs-extra/blob/master/lib/copy/copy.js. I initially thought that perhaps we could keep it running long enough to survive the v1.0.0 release, but I'm not sure.

> First error?

:+1: 

Should all the issues pertaining to ncp.js be consolidated into one issue tracking the rewrite?

**Comment by jprichardson** [comment] 2016-10-26 19:12
> Should all the issues pertaining to ncp.js be consolidated into one issue tracking the rewrite?

I'm fine with this. It's changed significantly since the original `ncp` and has many bugs fixed. My major concern with the rewrite is that it delays the release of 1.0.0. May be best to do it for 2.0.0. But if you feel differently, than I'm more than fine with it for 1.0.0.

**Comment by RyanZim** [comment] 2016-10-26 19:21
@jprichardson Not set on it, but I'm afraid fixing all the bugs in `ncp` is going to take longer than rewriting it. :grinning:

**Closed** 2016-10-27 14:47 UTC
Labels: feature-copy
