### ISSUE TITLE
Support memfs

### ISSUE THREAD

**Issue by vjpr** [jprichardson/node-fs-extra#503] opened 2017-10-29 18:42 UTC
It would be cool if the `fs` lib used was configurable. Does this lib rely on anything that would prevent `memfs` as a drop-in replacement for `fs`?

---

The workaround is to use `fs-monkey` to patch `fs`, and then `fs-extra`'s methods would use `memfs`.

**Comment by RyanZim** [comment] 2017-10-30 14:24
@vjpr This is basically a duplicate of https://github.com/jprichardson/node-fs-extra/issues/274; there's nothing that would make this impossible, it's just a matter of someone taking the time to do the needed coding. PR welcome.

**Closed by RyanZim** 2017-10-30 14:24 UTC
