### ISSUE TITLE
Optional argument for emptyDir to ignore files

### ISSUE THREAD

**Issue by reddishtg** [jprichardson/node-fs-extra#560] opened 2018-03-27 18:31 UTC
Is there any chance that we can add an additional optional argument to the `emptyDir` function for files that should not be passed to the remove function?  I imagine this could be an array that could be checked on each call to `deleteItem()`.

To be fair, this would be helpful in my current case, but I think it could be useful to others as well.  I imagine use cases such as configuration or hidden files in the directory as well that need to be left in place.

**Comment by RyanZim** [comment] 2018-03-27 20:09
Dupe of https://github.com/jprichardson/node-fs-extra/issues/527.

**Closed by RyanZim** 2018-03-27 20:09 UTC
