### ISSUE TITLE
fs.copy is different from 'cp -r'

### ISSUE THREAD

**Issue by ChenCody** [jprichardson/node-fs-extra#537] opened 2018-01-11 13:20 UTC
- **Operating System: Mac OS 10.13.2**
- **Node.js version: 8.2.1**
- **`fs-extra` version: 5.0.0**

The document in 'docs/copy.md' says
> 'Copy a file or directory. The directory can have contents. Like cp -r.' 
but in fact it is not.

Try this:
There is two folder called 'A' and 'B' like:
```
A--
 |-a1
 |-a2
```
```
B--
 |-b1
 |-b2
```

If I try `cp -r ./a ./b`, the folder 'B' will be like this:
```
B--
 |-b1
 |-b2
 |-A
   |-a1
   |-a2
```
And if i try `fs.copy('./a', './b')`, B will be like:
```
B--
 |-b1
 |-b2
 |-a1
 |-a2
```

These two command get different result. So i think the description 

> 'Copy a file or directory. The directory can have contents. Like cp -r.' 

in the document 'copy.md' is misleading.

I wish you could modify this document, and add some option that could make `fs.copy` achieve the same effect as 'cp -r'.

PS: Sorry for my poor English. : ）

**Comment by RyanZim** [comment] 2018-01-11 13:22
Dupe of https://github.com/jprichardson/node-fs-extra/issues/323; PR welcome to clarify docs.

**Closed by RyanZim** 2018-01-11 13:22 UTC

**Comment by ahuggins-nhsold** [comment] 2019-07-06 00:37
Recursive function which handily and easily solves this problem. No error handling, use at your risk as a starting point. Hope this helps others who come across this library, as it is fantastic and this is a really small sticking point.

```
const copyRecursiveSync = function copyRecursiveSync (src, dest) {
    fs.copySync(src, dest);

    fs.readdirSync(src)
        .map((name) => name)
        .filter((dir) => fs.lstatSync(path.join(src, dir)).isDirectory())
        .forEach((dir) => {
            copyRecursiveSync(path.join(src, dir), path.join(dest, dir));
            console.log(path.join(src, dir), path.join(dest, dir));
        });
};
```

**Comment by PawelWesolowski** [comment] 2020-09-01 12:47
another workaround 
```javascript
const fs = require('fs-extra');
const path = require('path');

const src = './from/here';
const dst = './to'; // will be copied to ./to/here

let newPath = path.join(dst, path.basename(src));
fs.emptyDirSync(newPath);
fs.copySync(src,newPath);
```
