### ISSUE TITLE
Error on run "npm start" from Loopback 4

### ISSUE THREAD

**Issue by gfernandes410** [jprichardson/node-fs-extra#783] opened 2020-03-30 00:58 UTC
I'm starting an Loopback 4 app and when I run "npm start" there is an error on several files from fs-extra.

file: fs-extra/lib/mkdirs/make-dir.js:86
``` cli
> getting-started@1.0.0 prestart /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> npm run build


> getting-started@1.0.0 build /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> lb-tsc

/home/gabriel/Documents/gabriel/loopback-getting-start/getting-started/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)`
```

file: fs-extra/lib/mkdirs/make-dir.js:135
```
> getting-started@1.0.0 prestart /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> npm run build


> getting-started@1.0.0 build /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> lb-tsc

/home/gabriel/Documents/gabriel/loopback-getting-start/getting-started/node_modules/fs-extra/lib/mkdirs/make-dir.js:135
      } catch {
              ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

file: fs-extra/lib/empty/index.js:33
```
> getting-started@1.0.0 prestart /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> npm run build


> getting-started@1.0.0 build /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> lb-tsc

/home/gabriel/Documents/gabriel/loopback-getting-start/getting-started/node_modules/fs-extra/lib/empty/index.js:33
  } catch {
          ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

file: fs-extra/lib/remove/rimraf.js:305
```
> getting-started@1.0.0 prestart /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> npm run build


> getting-started@1.0.0 build /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> lb-tsc

/home/gabriel/Documents/gabriel/loopback-getting-start/getting-started/node_modules/fs-extra/lib/remove/rimraf.js:305
      } catch {}
              ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

file: fs-extra/lib/ensure/file.js:47
```
> getting-started@1.0.0 prestart /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> npm run build


> getting-started@1.0.0 build /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> lb-tsc

/home/gabriel/Documents/gabriel/loopback-getting-start/getting-started/node_modules/fs-extra/lib/ensure/file.js:47
  } catch {}
          ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

file: fs-extra/lib/ensure/symlink-type.js:22
```
> getting-started@1.0.0 prestart /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> npm run build


> getting-started@1.0.0 build /home/gabriel/Documents/gabriel/loopback-getting-start/getting-started
> lb-tsc

/home/gabriel/Documents/gabriel/loopback-getting-start/getting-started/node_modules/fs-extra/lib/ensure/symlink-type.js:22
  } catch {
          ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

It's look like syntaxError and after I update the files above it worked! 

- **Operating System: ubunto 19.04 **
- **Node.js version: v9.11.2**
- **`fs-extra` version: fs-extra**

**Comment by manidlou** [comment] 2020-03-30 02:40
duplicate of #771.

**Closed by manidlou** 2020-03-30 02:40 UTC
