### ISSUE TITLE
Copy with filter stops processing after first false.

### ISSUE THREAD

**Issue by j** [jprichardson/node-fs-extra#603] opened 2018-07-12 20:11 UTC
```javascript
const assets = glob.sync(path.join(__dirname, '..', 'templates/**/assets/*'));

await fs.copy(
  path.join(__dirname, '..', 'templates'),
  path.join(__dirname, '..', 'build/assets'),
  {
    filter: (name) => {
      return assets.includes(name);
    }
  }
);
```

**Comment by RyanZim** [comment] 2018-07-17 00:38
Duplicate of https://github.com/jprichardson/node-fs-extra/issues/530.

**Closed by RyanZim** 2018-07-17 00:38 UTC
