### ISSUE TITLE
ensureDir(dir, callback) second callback parameter not specified

### ISSUE THREAD

**Issue by lexatnet** [jprichardson/node-fs-extra#182] opened 2015-10-09 08:30 UTC
second callback parameter not specified

```
fs.ensureDir(dir, function(err){
  //arguments.length ==2
})
```

**Comment by jprichardson** [comment] 2015-10-11 20:09
I'm not sure what the issue is?

**Comment by jprichardson** [comment] 2015-10-15 12:55
Closing, as not enough information provided. Please reopen if you would provide more info.

**Comment by triccardi-systran** [comment] 2015-11-23 11:43
The issue is missing documentation on the arguments passed to all the callbacks.
This information is especially useful when using `fs-extra` in `async.waterfall` where we need to know in advance how many arguments there will be on the callback.

Should I open a new issue or could this one be re-open?

**Comment by jprichardson** [comment] 2015-11-23 12:57
@triccardi-systran Makes sense. Done.

**Comment by RyanZim** [comment] 2017-04-08 18:45
Going to close this as a dupe of https://github.com/jprichardson/node-fs-extra/issues/349. https://github.com/jprichardson/node-fs-extra/issues/349 is newer, but it addresses the whole problem.

**Closed by RyanZim** 2017-04-08 18:45 UTC
Labels: documentation
