### ISSUE TITLE
Preserved timestamps include microseconds

### ISSUE THREAD

**Issue by ianbytchek** [jprichardson/node-fs-extra#732] opened 2019-11-07 10:28 UTC
- **Operating System:** macOS
- **Node.js version:** v12.12.0
- **`fs-extra` version:** 8.1.0

```js
fs.copySync(newImagePath, oldImagePath, {preserveTimestamps: true});
console.log(fs.statSync(newImagePath).mtimeMs); // 1573110917678
console.log(fs.statSync(oldImagePath).mtimeMs); // 1573110917677.5437
```

Comparing `mtime` produces false results, which can be a problem.

**Comment by RyanZim** [comment] 2020-01-30 16:16
Basically a dupe of https://github.com/jprichardson/node-fs-extra/issues/571; see discussion there.

**Closed by RyanZim** 2020-01-30 16:16 UTC
