### ISSUE TITLE
node_modules/fs-extra/lib/mkdirs/make-dir.js:86 create dir on fresh setup not working fine in relese 9.0.0

### ISSUE THREAD

**Issue by pankajcheema** [jprichardson/node-fs-extra#790] opened 2020-04-16 08:40 UTC
- **OS: Ubuntu 18.04:**

- **node js v8.16.0**
- **fs-extra version 9.0.0**

fixed once upgraded the node js version to **v12.16.1**

error was : 

```
/home/sahil/pankaj/xero-setup/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**Comment by hboylan** [comment] 2020-04-16 13:18
Can confirm I encounter the same issue on node v8

**Comment by RyanZim** [comment] 2020-04-16 14:15
Duplicate of https://github.com/jprichardson/node-fs-extra/issues/771; fs-extra v9 requires Node 10+

**Closed by RyanZim** 2020-04-16 14:15 UTC
