### ISSUE TITLE
Clarify docs for move's options 

### ISSUE THREAD

**Issue by valorloff** [jprichardson/node-fs-extra#348] opened 2017-01-26 15:34 UTC
```
fs.move(src,dest,[true],function(error) {
            if (error) throw error;
            console.log('Moved to '+dest);
          });
```
Error: EEXIST: file already exists   .....

**Comment by RyanZim** [comment] 2017-01-26 15:47
Docs should be clarified, correct usage of the overwrite option is: 
```js
fs.move(src,dest,{overwrite:true},function(error) {
  if (error) throw error;
  console.log('Moved to '+dest);
});
```
`options` must be an object.

Example: https://runkit.com/57ebc041d4a27f140028fd78/588a192238228e0015883bef.

**Comment by valorloff** [comment] 2017-01-26 15:49
nice!
thanks!

**Comment by valorloff** [comment] 2017-01-27 09:32
```
fs.move(oldFile, newFile,{owerwrite:true},(err)=>{
             if (err) throw err;
           });
```
```
Error: EEXIST: file already exists, link '/home/valaoffice/static/html/bla-bla.html' -> '/home/valaoffice/static/html/bla-bla-ma.html'
W20170127-11:18:11.649(2)? (STDERR)     at Error (native)
```
why?

**Comment by RyanZim** [comment] 2017-01-27 14:24
@valorloff  `link` is part of the move operation. What is the value of `oldFile` & `newFile` when this error occurs?

**Comment by valorloff** [comment] 2017-01-28 13:36
```
 if (err) throw err;   // 269
Error: EEXIST: file already exists, link '/home/valaoffice/static/html/k-t/s-p-200-m.html' -> '/home/valaoffice/static/html/d-m/s-p-200-m.html'
at Error (native)
```
moreover, moving file don't erase src file, and create new file only, this case above - exactly result of repeated fs.move

**Comment by RyanZim** [comment] 2017-01-28 13:46
What is the value of `oldFile` & `newFile` when this error occurs? Without this info, we cannot proceed to debug this.

**Comment by valorloff** [comment] 2017-01-28 13:59
console.log(src, dest);
src:  /home/valaoffice/static/html/aksessuary-dlya-mobilnyh-telefonov/Data-kabeli-adaptery/skotch-prozrachnyy-200-m.html 
dest:  /home/valaoffice/static/html/dlya-gazovoy-plity/skotch-prozrachnyy-200-m.html

**Comment by RyanZim** [comment] 2017-01-28 17:02
@valorloff I cannot reproduce this error. Please create a repository that demonstrates this error and post it to GitHub. Open a new issue with a link to the repo. Thanks!

**Comment by valorloff** [comment] 2017-01-30 07:35
I rewrite to:
```
if (!fs.existsSync(dest)) { // dest file not exist 
      if (!fs.existsSync(src)) {
      fs.writeFile(dest, SSR.render('productHtml'),
      function (err) {
        if (err) throw err;
        else  console.log('html file writed!');
      });
    } else {
      fs.rename(src,dest,(err)=>{
        if (err) throw err;
      })
    }
} else // dest file already exist
       	if (fs.existsSync(src)) {
       	  fs.rename(src,newHtmlFile,(err)=>{
          if (err) throw err;
        })
     }
```
and works perfectly for me, 
can it help you?

**Comment by lolmaus** [comment] 2017-02-19 16:16
I'm running into the same issue. `{overwrite: true}` does not prevent this:

> Error: EEXIST: file already exists, link '/home/lolmaus/Code/lolma-us/tmp/deploy-dist/staticboot/.nojekyll' -> '/home/lolmaus/Code/lolma-us/tmp/deploy-dist'

**Comment by lolmaus** [comment] 2017-02-19 16:21
Hmm, when this happens, the file `/home/lolmaus/Code/lolma-us/tmp/deploy-dist/.nojekyll` does not exist. O_o

**Comment by lolmaus** [comment] 2017-02-19 16:37
I replaced `move` with `rename` and it worked fine.

**Comment by RyanZim** [comment] 2017-04-08 18:41
Docs fixed in #384.

**Closed by RyanZim** 2017-04-08 18:41 UTC
Labels: documentation
