### ISSUE TITLE
ensureDir is difficult to promisify

### ISSUE THREAD

**Issue by Mr-Wallet** [jprichardson/node-fs-extra#325] opened 2016-12-07 22:26 UTC
Most promisification algorithms fail on `ensureDir` because the final parameter is `made` instead of `callback`. Currently in our project we must resort to `ensureDirSync` in all cases because our promisifier can't figure out what to do with `ensureDir`. Fortunately it's a very fast operation so users don't notice, but it's still making a few spots in our codebase look peculiar and require explanatory comments.

**Comment by jprichardson** [comment] 2016-12-08 03:43
Great point. This should be fixed. We'll be releasing 2.0 in early Jan. If you wanna submit a PR, I'd accept it for 2.0.

**Comment by Mr-Wallet** [comment] 2016-12-09 00:08
I put an hour or two into this and found that [bluebird](https://github.com/petkaantonov/bluebird/) does okay on `mkdirs` nit fails to promisify `ensureDir`, even after I implemented a change to put the callback onto the end.

The problem is not as straightforward as I had assumed. I suspect that something about the way things are required and exported is the culprit. `mkdirs` is one call to `require`, then `ensureDir` is another call to `require` (which should return the same cached reference), and then both get assigned onto the top-level exported module. I think somewhere in there something is resulting in some object reference tomfoolery where promisifiers _think_ they're iterating over every property, but don't actually touch ensureDir.

**Comment by RyanZim** [comment] 2016-12-09 01:04
@Mr-Wallet Just use https://github.com/overlookmotel/fs-extra-promise, perhaps?

**Comment by Mr-Wallet** [comment] 2016-12-09 15:29
We probably ought to! It's a large project though, so bumping up version on a dependency (like this one) is less risky than swapping one out wholesale. ;)

**Comment by RyanZim** [comment] 2016-12-09 23:44
@Mr-Wallet Understandable.

If you're not using bluebird, you will probably prefer https://github.com/kevinbeaty/fs-promise (I do).

**Comment by RyanZim** [comment] 2016-12-31 16:44
@jprichardson How should we be moving forward with this?

**Comment by RyanZim** [comment] 2017-01-02 14:18
> The problem is not as straightforward as I had assumed.

:+1: Since I'm not sure exactly what the problem is, I'm going to close this issue. If anyone figures out a sane way to improve this, PR welcome.

**Closed by RyanZim** 2017-01-02 14:18 UTC
Labels: enhancement
