### ISSUE TITLE
fs.copy incorrectly handling folder icons on OS X

### ISSUE THREAD

**Issue by alandickinson** [jprichardson/node-fs-extra#435] opened 2017-05-30 19:18 UTC
I have a folder that I'm copying with fs.copy that has an icon applied to it via a hidden Icon^M file. The folder is copied but the Icon^M is no longer hidden, and the new folder doesn't have the icon applied. I've tried hiding the file with chflags hidden. It hides the file but doesn't apply the icon. It seems like fs.copy should keep the folder intact when copying though. Any help is appreciated!

```javascript
var cwd = sh.pwd();
var base_file = __dirname + '/base.framer'
var destination_file = cwd.stdout + '/' + filename + '.framer'
fse.copy(base_file, destination_file, { overwrite: false, errorOnExist: true }, function(err) {
  if(err) {
    console.log(err);
  } else {
    console.log('copied');
  }
})
```

Updated to include some sample code.

**Comment by RyanZim** [comment] 2017-05-30 19:25
@jprichardson Can you test this; I don't have a Mac.

**Comment by jprichardson** [comment] 2017-05-30 21:28
@alandickinson can you provide instructions icons + folders? I've been using Macs for 10 years and sadly, I've never created a folder with an icon.

**Comment by alandickinson** [comment] 2017-05-31 02:38
@jprichardson Sure! [This article](https://support.apple.com/kb/PH22191?locale=en_US) explains how to set a custom image with copy and paste.

**Comment by alandickinson** [comment] 2017-07-06 20:30
Hey @jprichardson! Any progress on this? :)

**Comment by jprichardson** [comment] 2017-07-06 21:06
Sorry @alandickinson - I won't be able to make it a priority for awhile :( If you find the cause and the solution, we'll accept a PR though.

**Comment by RyanZim** [comment] 2017-10-18 14:34
Going to close this out as a `wontfix`, since it's not going to be a priority for the maintainers. Of course, if someone figures out a good solution and submits a PR, we'll definitely review it!

**Closed by RyanZim** 2017-10-18 14:34 UTC
Labels: feature-copy, needs-confirmed, platform-mac
