### ISSUE TITLE
fs.remove/fs.removeSync

### ISSUE THREAD

**Issue by yosef-123** [jprichardson/node-fs-extra#876] opened 2021-03-16 22:19 UTC
i have been able to use ths successfully in deleting huge folders but it dosnt delete .asar files and all its parent folders
ps it works on the rest of the directory just skips this file

**Comment by RyanZim** [comment] 2021-03-17 12:49
Platform? Node.js version? fs-extra version? Are you using fs-extra from within an electron app, or in plain Node.js?

**Comment by yosef-123** [comment] 2021-03-17 19:34
windows 10, 12.19.00, 9.1.0(latest),yes but uncompiled and compield
aka also doesnt work when i do npm start which runs 'electron .'

**Comment by RyanZim** [comment] 2021-03-18 15:03
Hmm, not sure what the issue is here. Have you verified you don't have a file permissions issue?

**Comment by RyanZim** [comment] 2021-03-18 17:00
Also, what's your electron version? This may be connected to https://github.com/electron/electron/issues/28195.

**Comment by yosef-123** [comment] 2021-03-18 21:06
6.14.8
and i dont think its cunnected becuse althogh i dont know so much about file securety im able to manually delete it.

**Comment by yosef-123** [comment] 2021-03-18 21:18
ps. windows thinks there is full access to read write delete ect...

**Comment by RyanZim** [comment] 2021-03-19 15:01
Honestly, I'm stumped here. Is it possible for you to create a reduced test case of this bug?

**Comment by yosef-123** [comment] 2021-03-19 15:11
heres my code. i don't  know what you mean.
im new to folder/file access (.ISjs = .js)

**Comment by RyanZim** [comment] 2021-03-19 18:49
Looks like you code wasn't included. Another name for a reduced test case is a minimal, complete, verifiable example; see more here: https://ibug.io/blog/2018/06/minimal-complete-verifiable-example/

**Comment by yosef-123** [comment] 2021-03-20 22:22
i redid different types of files ect and looked through windows security
and all access is same as all other files in the node_modules folder that
get deleted yet this doesnt

then i tried writing a .asar file and it got deleted so its not a bug
simply for this file not all .asar

so sorry for bothering you.
ps this is my .asar file thar doesnt delete (if you want it)

**Comment by yosef-123** [comment] 2021-03-20 22:26
[](url)

> 

![default_app](https://user-images.githubusercontent.com/66919967/111887183-f703da00-89db-11eb-80b9-daecbbf07af0.png)
ps its a .asar file just rename

**Comment by yosef-123** [comment] 2021-03-20 22:27
ps id still love if you can figure out how i can delete it or at least get a return like "1 files not deleted"

**Comment by yosef-123** [comment] 2021-03-21 21:24
do you know what to do about this file and others like it ?
like how to get higher access or something ?

**Comment by RyanZim** [comment] 2021-04-01 21:27
Unfortunately, I'm clueless here, and I have little chance of being able to debug this. For security reasons, I cannot download your `.asar` file, and you said the problem is specific to this file, so I'm at a dead-end here. Does `fs.remove` work to remove this specific file?

**Comment by RyanZim** [comment] 2021-04-15 20:27
Closing for lack of reply

**Closed by RyanZim** 2021-04-15 20:27 UTC
Labels: awaiting-reply, feature-remove
