### ISSUE TITLE
preserveTimestamps does not work

### ISSUE THREAD

**Issue by bchr02** [jprichardson/node-fs-extra#496] opened 2017-10-01 17:46 UTC
Using node v6.10.3 64bit Windows

The following does not preserve the last modified timestamp.

```javascript
const fse = require('fs-extra');
fse.copySync("test", "copy/test", { preserveTimestamps: true });
```

**Comment by manidlou** [comment] 2017-10-03 02:37
@bchr02 what is your operating system?

**Comment by RyanZim** [comment] 2017-10-03 14:23
What are the timestamps of the source and dest file?

**Comment by RyanZim** [comment] 2017-10-18 14:20
Closing for lack of reply.

**Comment by bchr02** [comment] 2017-12-01 21:51
It doesn't make a difference what the timestamps are or were. Did you try to reproduce?

**Comment by RyanZim** [comment] 2017-12-01 22:02
`fs-extra` is one of the top packages on npm, when we ship a regression, we usually hear about it pretty fast since it breaks so much of the ecosystem.

The reason I'm asking about what the timestamps are is that windows has a history of rounding errors. I want to see if the timestamps are at all close.

**Comment by bchr02** [comment] 2017-12-02 01:53
@RyanZim I didn't realize that. Thanks for the insight.

That being said, when I last tested this, there was _at least_ several days of time difference between the current time and the timestamp on the files.

Just curious, when you say "windows has a history of rounding errors" do you mean specifically node.js for Windows?

**Comment by RyanZim** [comment] 2017-12-02 14:20
I forget the details, but I think there's something that NTFS has only 1 or 2 sec. precision on 32-bit Windows; this causes slightly differing timestamps in some cases.

**Comment by RyanZim** [comment] 2018-02-05 18:33
I don't like doing this, but given that we haven't gotten any other reports of this, I'm going to close this. If anyone can track down the cause of this and submit a fix, they're welcome to, but it's not something the core team can devote time to.

**Closed by RyanZim** 2018-02-05 18:33 UTC
Labels: awaiting-reply, feature-copy, needs-confirmed, platform-windows

**Comment by bchr02** [comment] 2018-02-05 19:21
Have you tried to reproduce using the test case? It should confirm the bug. Not sure how you could close a reproducible error.

**Comment by manidlou** [comment] 2018-02-05 23:13
@bchr02 what are your src and dest? In your example, is `test` a file or directory?

**Comment by manidlou** [comment] 2018-02-05 23:20
Also @bchr02 how do you check the timestamps of your src and dest? can you give us more info to reproduce the case? I tested very quickly on windows 10  and it seems like it preserves the file timestamps.

**Comment by manidlou** [comment] 2018-02-05 23:21
BTW, @bchr02 are you using the latest `fs-extra` version?

**Comment by manidlou** [comment] 2018-02-06 00:12
@RyanZim I just noticed something! However It is not necessarily related to this issue, that's why I asked @bchr02 about the type of src and dest. 

Do we need to set the timestamps of directories that we create in the process of copying? because currently we just set their permissions. We only set the files timestamps.

https://github.com/jprichardson/node-fs-extra/blob/master/lib/copy/copy.js#L166

**Comment by RyanZim** [comment] 2018-02-06 15:17
@manidlou Not sure

**Comment by bchr02** [comment] 2018-02-07 04:43
@manidlou the src and dest are directories. I just tested using fs-extra@5.0.0 and the issue still exists. I tested with files instead of directories and the issue would not replicate. Therefore, the issue is limited to directories.

**Comment by fahadyaqubq** [comment] 2018-05-14 00:36
This issue does exist. When copying a directory with files to another directory, then the 'stats.mtime' is set to current time for all copied files.
