### ISSUE TITLE
 Cannot find module 'fs-extra/esm' or its corresponding type declarations.

### ISSUE THREAD

**Issue by jeffschwartz** [jprichardson/node-fs-extra#1033] opened 2024-01-30 16:07 UTC
node v20.11.0 LTS
- **Operating System:**
      macOS 14.3
- **Node.js version:**
      v20.11.0
- **`fs-extra` version:**
      fs-extra: v11.2.0
      @types/fs-extra: v11.0.4
-  typescript v5.1.3

When importing I get the following:

<img width="1920" alt="fs-extra" src="https://github.com/jprichardson/node-fs-extra/assets/271288/8303cc1a-ae1c-444b-bc03-85bed5c9188a">

**Comment by RyanZim** [comment] 2024-01-30 19:59
Duplicate of https://github.com/jprichardson/node-fs-extra/issues/979.

**Closed by RyanZim** 2024-01-30 19:59 UTC
