### ISSUE TITLE
CopySync readlinkSync Permission Denied with Electron Asar

### ISSUE THREAD

**Issue by klappy** [jprichardson/node-fs-extra#546] opened 2018-01-29 23:46 UTC
- **Operating System:** OSX, El Capitan, High Sierra
- **Node.js version:** v8.1.3
- **`fs-extra` version:** 5.0.0

Thanks for all of the great work on the project. It is a core dependency in almost all projects I use.
Recently when upgrading React to v16, we had to upgrade from fs-extra `v3.x`. So we upgraded to v5.0.0 and all appeared to be working well in our Electron app. That is until after we ran from our build. The problem did not happen in any Windows builds, just OSX.

For some reason when the Electron app attempted to copy from the Asar to the fs, it only made it a couple layers deep in the filesystem tree before reporting `permission denied` and `readlink` errors. After much debugging we realized that it was `v5.0.0` and downgraded to `v4.0.3` which met peer dependencies and all worked as it did before.

We were copying files that were in our application's Asar to a sub-directory in the user's path. The directory had a few directories before files were found in them. This didn't pose a problem for the first few parent directories as it got down to the first two layers with proper permissions. The third layer of directories appeared to be created but without proper permissions. Even in Finder, we are unable to open the directories due to permission errors.

The problem doesn't exist using npm start, just running from the output build where it has to copy from the directories in the Asar. It doesn't happen on Windows, just OSX. We tried builds created on different OSX versions and mixing where it was built and where it was installed. We were able to narrow it down to `fs-extra` `v5.0.0` using `copySync`. 

Another oddity, that might not be related at all is that it would randomly display errors on different paths and fail silently on others. It wasn't always consistent on which ones it showed, some of them even didn't get to the point where it created the broken paths, due to the syncronous usage of `copySync`, I thought it would stop execution after one but not a random 2 or 3. That could be our implementation. The other oddity is reporting problems copying a `.DS_Store` file in the path that didn't exist. We tried hunting it down and never could find it. That could be an issue with the build process and most likely not the library, but thought I'd share it in case it helps.

I apologize for not having a small standalone test case to recreate the issue so that it can be addressed. I do have screenshots of the errors when they happened. Even if this issue gets closed due to not providing enough data to recreate (a common open source community practice), this should still be posted for others encountering similar issues and save them time debugging.

![screen shot 2018-01-29 at 3 58 43 pm](https://user-images.githubusercontent.com/118073/35540549-69a272a0-0524-11e8-889e-fdf0f9dcf947.png)

<img width="542" alt="screen shot 2018-01-29 at 3 45 54 pm" src="https://user-images.githubusercontent.com/118073/35540359-87d87f90-0523-11e8-87e4-944c3d77994f.png">

**Comment by RyanZim** [comment] 2018-01-30 00:51
Thanks for the detailed report! We almost completely rewrote `copySync` in v5, so it doesn't surprise me that there's a few bugs here and there.

My first guess is that calling `fs.readlink()` on a regular file or directory results in `EACCES` on Mac in some cases. v4 and earlier only called it on symlinks.

Another thing I found in Wikipedia:

**Comment by RyanZim** [comment] 2018-01-30 00:56
Another thing; @klappy are we copying across volumes here?

**Comment by klappy** [comment] 2018-01-30 21:10
Thanks guys for the interest in helping add support. 

I noticed in the previous issues that were closed for copy/copySync that they appeared to be rewritten in v5. We think the .DS_Store issue was a red herring in that we attempted to bypass those and the problem still existed. However if the Asar creation somehow added those without them existing in the original codebase, that could be a clue.

@RyanZim My understanding of Asars is that they are treated as if they are a separate volume but I am not certain.

I wish it was easy to create a small use case to test these. As we try to adhere to TDD when encountering this issue we explored creating a test for this to ensure the problem can be tested before the build process but that led to a lengthy effort where our product owner didn't see that the juice was worth the squeeze when we could just downgrade it and move on. I'll do my best to keep up with this post and happy to help test it in our codebase if you feel you might have it addressed in a future release or even in a PR.

Thanks again guys! Keep up the good work, you're awesome :D

**Comment by manidlou** [comment] 2018-01-30 23:31
@klappy @RyanZim unfortunately I don't have a mac to test it myself. So, I appreciate if anyone can reproduce the error on their mac. However, these are my guesses so far:

The issue may be related to the fact of [limitations of the node API](https://electronjs.org/docs/tutorial/application-packaging#limitations-of-the-node-api) on asar packages. As it is written there:

> Though `asar` archives are treated as directories, there are no actual directories in the filesystem

Also,

> The `Stats` object returned by `fs.stat` and its friends on files in `asar` archives is generated by guessing, because those files do not exist on the filesystem. So you should not trust the `Stats` object except for getting file size and checking file type.

@klappy if it's possible, will you please give us an example of the arguments for src and dest that you pass to `fs.copySync()`?

**Comment by klappy** [comment] 2018-01-31 21:28
@manidlou: Here is where we were running into the issue, there is more than one occurrence in this file: https://github.com/unfoldingWord-dev/translationCore/blob/ab5cb0026700e923a74b9e4f2465c91d06b3ab92/src/js/helpers/ResourcesHelpers.js#L25

Before I downgraded, I attempted to pass the option: `{dereference: true}` but that didn't seem to make any difference.

**Comment by RyanZim** [comment] 2018-02-20 23:34
@manidlou What's your thoughts here?

**Comment by flexpaper** [comment] 2018-02-25 19:02
We have seen the same issue ourselves, essentially non-existing files on mac (not just in ASAR directories) are reported with EACCESS errorrs when the readlink method is called

**Comment by TheJaredWilcurt** [comment] 2018-02-25 19:59
A non-asar alternative would be to use NW.js. It's a more powerful alternative to Electron.

**Comment by evecalm** [comment] 2018-05-10 09:20
Same problem here.

Where I try to use `fs.copy` to copy a folder in `asar` package to outside, it threw an error
```js
{ Error: EACCES: permission denied, unlink '/Users/xxx/Library/Application Support/myapp/bin/darwin/readme.md'
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/Users/xxx/Library/Application Support/myapp/bin/darwin/readme.md' }
```

**Comment by manidlou** [comment] 2018-07-20 03:55
@klappy do you still experience the issue in `fs-extra` latest version `7.0.0`?

**Comment by manidlou** [comment] 2018-08-04 04:04
@klappy ping?!

**Comment by amxmln** [comment] 2018-08-10 21:26
I’m not sure if this is related or not, but my Electron application throws a ENOTDIR when trying to copy a folder from within the ASAR to a directory outside it. The destination folder gets created, however no contents are copied over. I even double-checked and the folder exists within the ASAR in the exact location.

During development everything works fine, it’s only once the application is built (and the folder becomes part of app.asar) that it throws the error, which is why I didn’t catch it until now.

**Comment by amxmln** [comment] 2018-08-11 08:35
That’s the error:

`{
  "errno":-20,
  "code":"ENOTDIR",
  "syscall":"copyfile",
  "path":"/home/username/Git/appname/build/linux-unpacked/resources/app.asar/dist/electron/static/foldername/filename.json",
  "dest":"/home/userame/path/to/dest/foldername/filename.json"
}`

(paths redacted for privacy)

It’s interesting that it includes the filenames in the error (which are the last file in the folder), but I’m calling copy() on the "foldername" folder.

**Comment by amxmln** [comment] 2018-08-12 08:15
I'm getting the ENOTDIR on 7.0.0 and the EACCESS when reverting to 4.0.3.

**Comment by manidlou** [comment] 2018-08-12 20:49
As much as I like us to fix this, but somehow my gut tells me `fs-extra` is not the cause of this issue rather it is more related to Electron's asar integration as @smashwilson (from atom team) mentioned in [#17273 (comment)](https://github.com/atom/atom/pull/17273#issuecomment-387473619):

>  I suspect the committing problem is a regression in Electron's asar integration - the fs-extra (or fs) module is no longer able to see directories within /Users/smashwilson/src/atom/atom/out/Atom.app/Contents/Resources/app.asar/.

**Comment by amxmln** [comment] 2018-08-25 21:35
Sorry for the absence, I was unable to work on my project for a while.

After doing some more testing, I found out that the error persists even with using copyFile from just fs—so I think your gut is right and it’s due to a regression in Electron. I guess we should file a bug there then?

**Comment by manidlou** [comment] 2018-08-29 05:43
@amxmln thanks for reporting the bug!

**Comment by manidlou** [comment] 2018-08-29 05:47
Closing this as the issue is most likely caused by the Electron asar integration and not `fs-extra`.

**Closed by manidlou** 2018-08-29 05:47 UTC
Labels: feature-copy, needs-confirmed, platform-mac
