### ISSUE TITLE
copySync doesn't apply the filter to directories

### ISSUE THREAD

**Issue by dbountsman** [jprichardson/node-fs-extra#244] opened 2016-05-04 13:14 UTC
copySync has a bug, it evaluates the filter only for files. The directoies are copied unfiltered. 
The asynchronous copy method evaluates the filter correct.

**Comment by paulhocker** [comment] 2016-05-25 03:29
+1

copy uses NCP - copySync does a recursive call on itself - the smarts of NCP would need to be added to this funtion

**Comment by icefox0801** [comment] 2016-05-26 05:45
+1

**Comment by raulggonzalez** [comment] 2016-08-02 09:10
+1

**Comment by RyanZim** [comment] 2016-10-26 19:55
Oops, duplicate of https://github.com/jprichardson/node-fs-extra/issues/180.

**Closed by RyanZim** 2016-10-26 19:55 UTC
