### ISSUE TITLE
move with clobber option 'ENOTEMPTY'

### ISSUE THREAD

**Issue by newmanw** [jprichardson/node-fs-extra#124] opened 2015-04-08 19:11 UTC
I am trying to move a directory using the move function:

```javascript
      fs.move("somdir", "otherdir", {clobber: true}, function(err) {
        if (err) {
          console.log('error moving', err)
        }
        ...
      });
```

other dir is a directory that has a bunch of stuff already in it.

I get the following error:
Error: ENOTEMPTY,

**Comment by jprichardson** [comment] 2015-04-09 18:46
Are you using the latest `fs-extra` version? Which operating system? Which Node version? This should work: https://github.com/jprichardson/node-fs-extra/blob/0.18.0/test/move.test.js#L224

**Comment by jprichardson** [comment] 2015-06-21 15:12
Closing, please reopen if still having the issue.

**Closed by jprichardson** 2015-06-21 15:12 UTC

**Comment by monolithed** [comment] 2016-11-22 18:27
I've got the same error message. 

```
Error: ENOTEMPTY: directory not empty, rmdir '/var/lib/selenium/jenkins-slave/workspace/yoda.runner/tests/node_modules'
```

```
➜ node -v
v7.0.1

➜ npm -v
3.10.10

Ubuntu
```

**Comment by RyanZim** [comment] 2016-11-22 18:33
@monolithed What version of fs-extra? Please post the code that produces this error.

**Comment by monolithed** [comment] 2016-11-22 20:05
@RyanZim, 

> What version of fs-extra? 

`fs-extra@1.0.0`

> Please post the code that produces this error.

```js
{
	moveCache () {
		let { cache } = this.options;
		let { temporary, workspace } = this.modulePaths;

		debug(`replacing outdated modules ${temporary} => ${workspace}`);

		fs.move(temporary, workspace, { clobber: true }, error => {
			if (error) {
				throw `Could not replace outdated modules ${temporary}\n${error}`;
			}

			fs.remove(cache, () => {
				debug(`removing a temporary directory: ${cache}`);
			});

			debug('completed');
		});
	}
}
```

```
21:17:09 Tue, 22 Nov 2016 18:17:09 GMT @qa:npm-cache replacing outdated modules /tmp/dada28a1048095cb5ab9ccdf38101ce8/node_modules => /var/lib/selenium/jenkins-slave/workspace/yoda.runner/tests/node_modules
21:17:17 
21:17:17 /var/lib/selenium/jenkins-slave/workspace/yoda.runner/tests/node_modules/@qa/npm-cache/index.js:276
21:17:17 				throw `Could not replace outdated modules ${temporary}\n${error}`;
21:17:17 				^
21:17:17 Could not replace outdated modules /tmp/dada28a1048095cb5ab9ccdf38101ce8/node_modules
21:17:17 Error: ENOTEMPTY: directory not empty, rmdir '/var/lib/selenium/jenkins-slave/workspace/yoda.runner/tests/node_modules'
```

**Comment by RyanZim** [comment] 2016-11-22 20:56
I can't reproduce on Lubuntu (Ubuntu with LXDE DE).

My guess is that this is related to https://github.com/isaacs/rimraf/issues/25. Most likely something is writing to the directory while the move is in progress.
