### ISSUE TITLE
Support ESModules and named exports

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [jprichardson/node-fs-extra#838] opened 2020-10-09 22:54 UTC
- **Operating System:** Windows
- **Node.js version:** 14
- **`fs-extra` version:** 9.0.1

With the node.js `fs` module, I like importing specific functions like this:
```js
import { createWriteStream } from 'fs'
```

It would be nice if `fs-extra` also had named exports, which are an ESModules feature:
```js
// This is a feature that doesn't currently exist, but it should
import { emptyDir } from 'fs-extra'
```

**Comment by RyanZim** [comment] 2020-10-09 23:11
ESM is still officially experimental in Node, and is based on https://github.com/isaacs/node-graceful-fs, which does not yet have ESM support. I'd like to support this in the future, but it probably won't happen right away. Closing as duplicate of https://github.com/jprichardson/node-fs-extra/issues/746.

**Closed by RyanZim** 2020-10-09 23:11 UTC

**Comment by lvjiaxuan** [comment] 2024-03-01 09:17
Dust Falls.
