### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by edwlook** [jprichardson/node-fs-extra#782] opened 2020-03-28 23:18 UTC
- **Operating System:** Ubuntu 18.04.4 LTS

- **Node.js version:** v12.16.1
- **`fs-extra` version:** ^9.0.0

```
> node ./main.js

.../node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
```

Looks like it should be `catch (e) {` ?

**Comment by alias-rahil** [comment] 2020-03-29 00:47
You will need to change line 86 of [this](https://github.com/jprichardson/node-fs-extra/blob/master/lib/mkdirs/make-dir.js) file to:

`} catch(error) {`

**Comment by manidlou** [comment] 2020-03-29 00:55
duplicate of #771.

**Closed by manidlou** 2020-03-29 00:55 UTC

**Comment by geneparcellano** [comment] 2020-08-19 05:47
I'm still having the same issue on:

- fs-extra: v9.0.1
- node: v12.1.0

After replacing `} catch {` with `} catch(error) {` in multiple files, it's finally working.

**Comment by RyanZim** [comment] 2020-08-20 17:30
@geneparcellano What's your setup? Do you have babel or some bundler in your setup? What's the exact error message you're getting?

**Comment by dnasir** [comment] 2020-09-18 14:45
I'd like to report the same issue when running jest on TeamCity. Here are the CI server details:

* node: v12.16.1
* fs-extra: 9.0.1

Here's the relevant error log:

```
C:\BuildAgent1\work\e7499cbf9ff8fce2\src\RTMap.Web\node_modules\fs-extra\lib\mkdirs\make-dir.js:85

          } catch {
                  ^
    
    SyntaxError: Unexpected token {
        at createScript (vm.js:80:10)
        at Object.runInThisContext (vm.js:139:10)
        at Module._compile (module.js:617:28)
        at Object.Module._extensions..js (module.js:664:10)
        at Module.load (module.js:566:32)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)
        at Module.require (module.js:597:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (C:\BuildAgent1\work\e7499cbf9ff8fce2\src\RTMap.Web\node_modules\fs-extra\lib\mkdirs\index.js:3:44)
```

FYI I'm running jest via `vue-cli-service`.

**Comment by RyanZim** [comment] 2020-09-18 14:47
Is your CI server actually on Node v12?

**Comment by dnasir** [comment] 2020-09-18 15:01
> Is your CI server actually on Node v12?

Turns out TC was reporting the wrong node version. I checked again, and sure enough, it was running v8 for some reason.

It's running fine now. Thanks.
