### ISSUE TITLE
fs-extra v9 causing tests using proxyquire to fail 

### ISSUE THREAD

**Issue by rvillane** [jprichardson/node-fs-extra#787] opened 2020-04-01 16:49 UTC
- **Node.js version:**. v10
- **`fs-extra` version:**  9.0.0

Error found in logs:

/home/jenkins/workspace/il-transaction-comparator_master/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
} catch {
^

SyntaxError: Unexpected token {
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:617:28)
at Module.replacementCompile (/home/jenkins/workspace/il-transaction-comparator_master/node_modules/append-transform/index.js:60:13)
at Module._extensions..js (module.js:664:10)
at Object..js (/home/jenkins/workspace/il-transaction-comparator_master/node_modules/append-transform/index.js:64:4)
at require.extensions.(anonymous function) (/home/jenkins/workspace/il-transaction-comparator_master/node_modules/proxyquire/lib/proxyquire.js:311:43)
at Object. (/home/jenkins/workspace/il-transaction-comparator_master/node_modules/append-transform/index.js:64:4)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)

As a workaround, I downgrade fs-extra from v9.0.0 to v8.1.0 and then it works fine.

any ideas ?

**Comment by JPeer264** [comment] 2020-04-01 17:39
Seems like you have a Node version older than 10. 

Duplicate of #771

**Closed by JPeer264** 2020-04-01 17:39 UTC

**Comment by RyanZim** [comment] 2020-04-01 18:18
That, or you need to upgrade proxyquire.

**Comment by rvillane** [comment] 2020-04-01 18:41
thanks for the responses, actually just discovered the Jenkins slave running the builds has node 8, which explains the error.
