### ISSUE TITLE
ENOSYS: function not implemented, link

### ISSUE THREAD

**Issue by kadishmal** [jprichardson/node-fs-extra#263] opened 2016-07-28 04:50 UTC
I don't know if I should report this error or not, whether this error is caused by the network file system that we use or not, anyway, here it is.
- `fs-extra v0.26.7`
- Node `v4.4.7`
  
  ```
  Trace: { [Error: ENOSYS: function not implemented, link '/mnt/cufs/webapp/1.5.2.340/Windows/1469676305/App.pdb.orig' -> '/mnt/cufs/webapp/1.5.2.340/Windows/1469676305/App.pdb/52913A3B6F9F470480D2EC20E854A8141/App.sym']
     errno: -38,
     code: 'ENOSYS',
     syscall: 'link',
     path: '/mnt/cufs/webapp/1.5.2.340/Windows/1469676305/App.pdb.orig',
     dest: '/mnt/cufs/webapp/1.5.2.340/Windows/1469676305/App.pdb/52913A3B6F9F470480D2EC20E854A8141/App.sym' }
       at /home1/user/openapi-2.0.0/lib/projects/Parser/Elf/elf-parser.js:123:20
       at /home1/user/openapi-2.0.0/node_modules/async/lib/async.js:52:16
       at done (/home1/user/openapi-2.0.0/node_modules/async/lib/async.js:241:17)
       at /home1/user/openapi-2.0.0/node_modules/async/lib/async.js:44:16
       at /home1/user/openapi-2.0.0/node_modules/fs-extra/lib/move/index.js:73:11
       at FSReqWrap.oncomplete (fs.js:82:15)
   Trace: { [Error: ENOSYS: function not implemented, link '/mnt/cufs/webapp/1.5.2.340/Windows/1469676305/App.pdb.orig' -> '/mnt/cufs/webapp/1.5.2.340/Windows/1469676305/App.pdb/52913A3B6F9F470480D2EC20E854A8141/App.sym']
  ```

The problem code line is [`fs-extra/lib/move/index.js:73:11`](https://github.com/jprichardson/node-fs-extra/blob/master/lib/move/index.js#L73). This means that the underlying FS doesn't support the `fs.link` operation.

However, when I switch back to Node `v0.12.x` with `fs-extra v0.26.7`, the `fs.link` operation doesn't trigger the error which is weird.

The workaround was to provide the `clobber: true` option so that it calls the `fs.rename` function instead. From this I guess that if the destination file exists, the `fs.link` fails with the above error which is counterintuitive.

**Comment by RyanZim** [comment] 2016-10-25 16:51
@jprichardson Thoughts?

**Comment by jprichardson** [comment] 2016-10-25 16:53
There isn't enough info here to reproduce anything. I do know that I've had a heck of a time with `fs.link` and `fs.rename` on Windows and debugging issues in the past. Network FS just makes it trickier.

**Comment by RyanZim** [comment] 2016-10-25 16:55
@kadishmal Is this still an issue? If so, could you provide more context?

**Comment by kadishmal** [comment] 2016-10-31 09:47
Well, it's not an issue now because I'm passing the `clobber: true` option which bypasses the `fs.link()` command. If I don't pass, this issue occurs.

**Comment by RyanZim** [comment] 2016-10-31 15:03
I'll try to dig into this when I get time.

**Comment by RyanZim** [comment] 2016-12-31 15:17
FWIW, I don't know when I'll get time for this. :grinning:

**Comment by RyanZim** [comment] 2017-02-18 16:19
Since no one else seems to have encountered this issue, I am going to close this. If someone has this issue, please open a new issue thread.

**Closed by RyanZim** 2017-02-18 16:19 UTC
Labels: needs-confirmed
