### ISSUE TITLE
move() not work when dest name not provided

### ISSUE THREAD

**Issue by mawni** [jprichardson/node-fs-extra#311] opened 2016-11-13 12:27 UTC
As I've been working on `moveSync` function, I noticed something about how the `move` function does its job. I'd like this to be clarified for myself since I want the `moveSync` to be consistent with `move`.

When you do something like,

```javascript
const fs = require('fs-extra')
fs.move('./source/somefile.txt', './source/otherDir/somefile.txt', callback)
```
it works just fine.

But, when you do like,
```javascript
const fs = require('fs-extra')
fs.move('./source/somefile.txt', './source/otherDir', callback)
```
nothing happens.

However, if you run the same examples using Linux `mv` command on a Terminal, the move operation occurs.

Is this an expected behavior from `move` function?

Thanks.

**Comment by jprichardson** [comment] 2016-11-13 18:10
> Is this an expected behavior from move function?

It's a common misconception that functions in `fs-extra` should behave like their Unix counterparts. I understand that because the introduction in the README discusses the Unix counterparts. However, I believe that we as programmers should be explicit as writing code is easy but going back and reading code is hard.

```js
fs.move('./source/somefile.txt', './source/otherDir', callback)
```

This not working is the expected behavior. However, it really shouldn't silently fail. It should probably throw an `EEXIST` error. 

What are your thoughts @RyanZim?

**Comment by mawni** [comment] 2016-11-13 18:46
> However, it really shouldn't silently fail. It should probably throw an EEXIST error.

I think that'd be very helpful in order to point out to the user that you are probably using the function incorrectly that you are getting this error.

**Comment by mawni** [comment] 2016-11-13 21:15
Also, definitely agree with this,

> However, I believe that we as programmers should make our intentions explicit as writing code is easy but going back and reading code is hard.

Very good point.

**Comment by RyanZim** [comment] 2016-11-14 14:00
:+1: For throwing an error, :-1: for throwing an `EEXIST` error.

It should throw an error, but it should be a custom error, clearly explaining what the problem is.

> I think that'd be very helpful in order to point out to the user that you are probably using the function incorrectly that you are getting this error.

I don't think we should need to document what our errors mean. The error message should make it self-evident what the error is about. For that reason, I oppose an `EEXIST` error.

Not to mention the fact that "faking" a system error isn't easy, and system errors can't be totally replicated by userland code.

Perhaps something like this would be better:
```
Error: fs-extra: move() does not support specifying a directory as a target when copying a file.
```

**Comment by jprichardson** [comment] 2016-11-14 15:33
> I don't think we should need to document what our errors mean. The error message should make it self-evident what the error is about. For that reason, I oppose an EEXIST error.

I think this is great.

> Error: fs-extra: move() does not support specifying a directory as a target when copying a file.

This is going to change in some cases. This is valid if the source is file and dest a dir.

What about these cases (dest exists in all cases):

- source is file, dest is file?
- source is dir, dest is dir?
- source is dir, dest if file?

**Comment by RyanZim** [comment] 2016-11-14 15:45
OK, yeah. Don't have time ATM to investigate all this; if you can look into/implement this, great! If not, I will try to get to it sometime.

**Comment by jprichardson** [comment] 2016-11-14 15:52
> OK, yeah. Don't have time ATM to investigate all this; if you can look into/implement this, great! If not, I will try to get to it sometime.

No prob.

**Comment by RyanZim** [comment] 2016-12-31 16:43
@jprichardson @mawni Just started fooling with this; I'm not seeing any problems. It throws an EEXIST error just fine: https://runkit.com/57ebc041d4a27f140028fd78/5867de8c9b47a300142622ee.

**Comment by mawni** [comment] 2017-01-01 11:24
That's right. I tested it just right now. It throws an EEXIST error. Also,

> What about these cases (dest exists in all cases):

>  source is file, dest is file?
> source is dir, dest is dir?
> source is dir, dest if file?


I tested for all these cases too and for all them it throws an EEXIST error.

**Comment by RyanZim** [comment] 2017-01-02 13:58
Good to hear, closing.

**Closed by RyanZim** 2017-01-02 13:58 UTC
Labels: feature-move
