### ISSUE TITLE
inconsistency in return type `read()` between module and TypeScript definition.

### ISSUE THREAD

**Issue by Borewit** [jprichardson/node-fs-extra#448] opened 2017-06-24 18:07 UTC
The return value of the promisified read(...) and the [TypeScript definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/fs-extra/index.d.ts) is inconsistent.

read returns a `Promise<number>` while TypeScript definition declares a `Promise<[number, Buffer]>`. 

The TypeScript definition does make sense, since Node's documented return value is: [(err, bytesRead, buffer)](https://nodejs.org/api/fs.html#fs_fs_read_fd_buffer_offset_length_position_callback).

How can this inconsistency be solved? Change the TypeScript definition or node-fs-extra?

**Comment by RyanZim** [comment] 2017-06-24 19:12
Basically a dupe of https://github.com/jprichardson/node-fs-extra/issues/436; merging in there.

**Closed by RyanZim** 2017-06-24 19:12 UTC
