### ISSUE TITLE
include TypeScript declarations

### ISSUE THREAD

**Issue by alex-at-cascade** [jprichardson/node-fs-extra#606] opened 2018-07-31 16:46 UTC
This is a great package.  It would be **even more** wonderful if the `.d.ts` files could be shipped with the package (e.g., similarly to how `aws-sdk` does it).  Jetbrains tools (WebStorm, etc.) make effective use of them when they're included in the package (it can make using the package a lot more efficient).  Thanks!

**Comment by RyanZim** [comment] 2018-07-31 17:54
Dupe of https://github.com/jprichardson/node-fs-extra/issues/468.

**Closed by RyanZim** 2018-07-31 17:54 UTC
