### ISSUE TITLE
copySync throw error when directory has unreachable symlinks

### ISSUE THREAD

**Issue by lljxx1** [jprichardson/node-fs-extra#765] opened 2020-02-24 03:37 UTC
- **Operating System:**
mac
- **Node.js version:**
v12.14.0
- **`fs-extra` version:**
8.1.0

error line:
https://github.com/jprichardson/node-fs-extra/blob/master/lib/copy-sync/copy-sync.js#L121

function `copyDirItem` `stat.checkPathsSync` should be use fs.lstatSync when options:`dereference` is false

**Comment by lljxx1** [comment] 2020-02-24 04:06
quick fix
util/stat.js:getStatsSync
``` javscript
function getStatsSync (src, dest, opts = {}) {
  let srcStat, destStat
  const statSync = opts.dereference ? fs.statSync : fs.lstatSync
  if (nodeSupportsBigInt()) {
    srcStat = statSync(src, { bigint: true })
  } else {
    srcStat = statSync(src)
  }
  try {
    if (nodeSupportsBigInt()) {
      destStat = statSync(dest, { bigint: true })
    } else {
      destStat = statSync(dest)
    }
  } catch (err) {
    if (err.code === 'ENOENT') return { srcStat, destStat: null }
    throw err
  }


  return { srcStat, destStat }
}
```

**Comment by RyanZim** [comment] 2020-02-24 14:02
@manidlou Can you take a look at this?

**Comment by manidlou** [comment] 2020-02-25 20:29
Sure thing!

**Comment by manidlou** [comment] 2020-02-25 20:33
@lljxx1 can you give us a reproducible test case please?

**Comment by lljxx1** [comment] 2020-02-27 05:51
``` bash
fundembp:alternatives fun$ ls -l
total 0
lrwxr-xr-x  1 fun  staff  31  2 24 09:57 phar -> /code/.fun/root/usr/bin/phar7.0
lrwxr-xr-x  1 fun  staff  47  2 24 09:57 phar.1.gz -> /code/.fun/root/usr/share/man/man1/phar7.0.1.gz
lrwxr-xr-x  1 fun  staff  36  2 24 09:57 phar.phar -> /code/.fun/root/usr/bin/phar.phar7.0
lrwxr-xr-x  1 fun  staff  52  2 24 09:57 phar.phar.1.gz -> /code/.fun/root/usr/share/man/man1/phar.phar7.0.1.gz
lrwxr-xr-x  1 fun  staff  30  2 24 09:57 php -> /code/.fun/root/usr/bin/php7.0
lrwxr-xr-x  1 fun  staff  34  2 24 09:57 php-cgi -> /code/.fun/root/usr/bin/php-cgi7.0
lrwxr-xr-x  1 fun  staff  38  2 24 09:57 php-cgi-bin -> /code/.fun/root/usr/lib/cgi-bin/php7.0
lrwxr-xr-x  1 fun  staff  50  2 24 09:57 php-cgi.1.gz -> /code/.fun/root/usr/share/man/man1/php-cgi7.0.1.gz
lrwxr-xr-x  1 fun  staff  46  2 24 09:57 php.1.gz -> /code/.fun/root/usr/share/man/man1/php7.0.1.gz
```

here is the example,  the `/code` folder is not exists

**Comment by oznu** [comment] 2020-03-07 00:25
I've encounted this issue as well.

Online demo reproducing the issue: https://repl.it/repls/OvalCruelApplets

**Comment by tomasreimers** [comment] 2020-08-20 18:43
As a quick workaround to anyone who also found this issue but doesn't want to patch node modules locally, https://www.npmjs.com/package/ncp seems to be a fine alternative for copy. 

With that said, it seems the fix was just merged into v10, so hopefully this should be closed out soon! :)

**Comment by RyanZim** [comment] 2021-04-01 20:17
Fixed in https://github.com/jprichardson/node-fs-extra/pull/779

**Closed by RyanZim** 2021-04-01 20:17 UTC
Labels: feature-copy
